"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const course_controller_1 = require("../course/course.controller");
const infrastructure_1 = require("../../infrastructure");
const infrastructure_2 = require("../../infrastructure");
const TokenValidator_1 = require("../services/TokenValidator");
const router = (0, express_1.Router)();
const dataSource = new infrastructure_1.CourseDataSourceImpl();
const courseRepository = new infrastructure_2.CourseRepositoryImpl(dataSource);
const courseController = new course_controller_1.CourseController(courseRepository);
router.get("/", courseController.getCourses);
router.get("/:id", courseController.getCourseById);
router.put("/:id", TokenValidator_1.ValidatorTo.ValidarToken, courseController.updateCourseById);
module.exports = router;
