"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const enrollment_controller_1 = require("../enrollment/enrollment.controller");
const datasource_1 = require("../../infrastructure/datasource/");
const repositories_1 = require("../../infrastructure/repositories/");
const router = (0, express_1.Router)();
const dataSource = new datasource_1.EnrollmentDataSourceImpl();
const enrollmentRepository = new repositories_1.EnrollmentRepositoryImpl(dataSource);
const enrollmentController = new enrollment_controller_1.EnrollmentController(enrollmentRepository);
router.get("/academic-status/:seminarian_id", enrollmentController.getAcademicStatus);
router.get("/seminarian-stage/", enrollmentController.getStageOfSeminarian);
router.get("/equivalency-list/:seminarian_id", enrollmentController.getSubjectAllowToEnrollEquivalency);
router.get("/seminarian-academic-term/", enrollmentController.getAcademicTermByEnrollment);
router.post("/create-by-equivalence/", enrollmentController.createEnrollmentByEquivalence);
router.post("/", enrollmentController.create);
router.get("/", enrollmentController.get);
router.put("/:id", enrollmentController.update);
router.delete("/:id", enrollmentController.delete);
module.exports = router;
