"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const instructor_controller_1 = require("../instructor/instructor.controller");
const infrastructure_1 = require("../../infrastructure");
const infrastructure_2 = require("../../infrastructure");
const TokenValidator_1 = require("../services/TokenValidator");
const router = (0, express_1.Router)();
const datasource = new infrastructure_1.InstructorDataSourceImple();
const instructorRepository = new infrastructure_2.InstructorRepositoryImpl(datasource);
const instructorController = new instructor_controller_1.InstructorController(instructorRepository);
router.get("/ficha/:id", instructorController.ficha);
router.post("/", TokenValidator_1.ValidatorTo.ValidarToken, instructorController.createInstructor);
router.get("/", TokenValidator_1.ValidatorTo.ValidarToken, instructorController.getInstructors);
router.get("/:id", TokenValidator_1.ValidatorTo.ValidarToken, instructorController.getInstructorById);
router.put("/:id", TokenValidator_1.ValidatorTo.ValidarToken, instructorController.updateInstructorById);
router.delete("/:id", TokenValidator_1.ValidatorTo.ValidarToken, instructorController.deleteInstructor);
module.exports = router;
