"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const stage_controller_1 = require("../stage/stage.controller");
const infrastructure_1 = require("../../infrastructure/");
const infrastructure_2 = require("../../infrastructure/");
const TokenValidator_1 = require("../services/TokenValidator");
const router = (0, express_1.Router)();
const datasource = new infrastructure_1.StageDataSourceImple();
const stageRepository = new infrastructure_2.StageRepositoryImpl(datasource);
const stageController = new stage_controller_1.StageController(stageRepository);
router.get("/", TokenValidator_1.ValidatorTo.ValidarToken, stageController.getStages);
router.get("/:id", TokenValidator_1.ValidatorTo.ValidarToken, stageController.getStageById);
module.exports = router;
