"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const test_controller_1 = require("../test/test.controller");
const datasource_1 = require("../../infrastructure/datasource/");
const repositories_1 = require("../../infrastructure/repositories/");
const router = (0, express_1.Router)();
const dataSource = new datasource_1.TestDataSourceImpl();
const testRepository = new repositories_1.TestRepositoryImpl(dataSource);
const testController = new test_controller_1.TestController(testRepository);
router.get("/notas/:id", testController.notas);
router.get("/by-subject/", testController.getTestBySubject);
router.get("/for-test-score/", testController.getTestForTestScore);
router.get("/average-test-score-by-subject/", testController.getAverageGradeBySubject);
router.get("/lista", testController.SeminarianListWithNotes);
router.post("/", testController.create);
router.get("/", testController.get);
router.put("/:id", testController.update);
router.delete("/:id", testController.delete);
module.exports = router;
