"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const test_controller_1 = require("../test/test.controller");
const datasource_1 = require("../../infrastructure/datasource/");
const repositories_1 = require("../../infrastructure/repositories/");
const TokenValidator_1 = require("../services/TokenValidator");
const router = (0, express_1.Router)();
const dataSource = new datasource_1.TestDataSourceImpl();
const testRepository = new repositories_1.TestRepositoryImpl(dataSource);
const testController = new test_controller_1.TestController(testRepository);
router.get("/notas/:id", TokenValidator_1.ValidatorTo.ValidarToken, testController.notas);
router.get("/by-subject/", TokenValidator_1.ValidatorTo.ValidarToken, testController.getTestBySubject);
router.get("/for-test-score/", TokenValidator_1.ValidatorTo.ValidarToken, testController.getTestForTestScore);
router.get("/average-test-score-by-subject/", TokenValidator_1.ValidatorTo.ValidarToken, testController.getAverageGradeBySubject);
router.get("/lista", TokenValidator_1.ValidatorTo.ValidarToken, testController.SeminarianListWithNotes);
router.post("/", TokenValidator_1.ValidatorTo.ValidarToken, testController.create);
router.get("/", TokenValidator_1.ValidatorTo.ValidarToken, testController.get);
router.put("/:id", TokenValidator_1.ValidatorTo.ValidarToken, testController.update);
router.delete("/:id", TokenValidator_1.ValidatorTo.ValidarToken, testController.delete);
module.exports = router;
