"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const infrastructure_1 = require("../../infrastructure");
const user_controller_1 = require("../user/user.controller");
const TokenValidator_1 = require("../services/TokenValidator");
const login_1 = require("../validators/login");
const router = (0, express_1.Router)();
const datasource = new infrastructure_1.UserDataSourceImplementation();
const Repository = new infrastructure_1.UserRepositoryImpl(datasource);
const UserControl = new user_controller_1.UserControler(Repository);
router.get('/', TokenValidator_1.ValidatorTo.ValidarToken, UserControl.getAll);
router.get("/user-by-type/", UserControl.getByType);
router.get("/:id", UserControl.getById);
router.post('/Login/', login_1.ValidatorLogin, UserControl.Login);
router.post('/logout', TokenValidator_1.ValidatorTo.Eliminate);
router.post('/reset', TokenValidator_1.ValidatorTo.ValidarToken, UserControl.Reset);
router.post('/pass', TokenValidator_1.ValidatorTo.ValidarToken, login_1.ValidatorLogin, UserControl.ChangePass);
module.exports = router;
